source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'bcrypt'
gem "twitter-bootstrap-rails"
gem "font-awesome-rails"

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'

  gem 'web-console', '~> 2.0'
end

