source 'https://rubygems.org'


gem 'dotenv-rails', :groups => [:development, :test]
gem 'oauth2'
gem 'httparty'
gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'bcrypt'
gem "twitter-bootstrap-rails"
gem "font-awesome-rails"
gem 'awesome_print'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'

  gem 'web-console', '~> 2.0'
end

